spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/?readPreference=primary&appname=MongoDB%20Compass&ssl=false
      host: localhost
      port: 27017
      database: FuelApp_DB
server:
  port: 8084

  kafka:
    bootstrap-servers: 9092
